[workspace]
members = ["boring", "boring-sys", "tokio-boring"]
resolver = "2"

[workspace.package]
version = "0.2.0-alpha.1"
repository = "https://github.com/plabayo/rama-boring"
# we should stick on edition 2021 until ecosystem is ready,
# and perhaps let cloudflare do it if ever,
# for now let's stick to 2021 with MSRV 1.82
edition = "2021"

[workspace.metadata.release]
pre-release-commit-message = "Release {{version}}"
shared-version = true
tag-prefix = ""
publish = false

[workspace.dependencies]
rama-boring-sys = { version = "0.2.0-alpha.1", path = "./boring-sys" }
rama-boring = { version = "0.2.0-alpha.1", path = "./boring" }
rama-boring-tokio = { version = "0.2.0-alpha.1", path = "./tokio-boring" }

bindgen = { version = "0.71.1", default-features = false, features = [
    "runtime",
] }
bytes = "1"
cmake = "0.1.18"
fs_extra = "1.3.0"
fslock = "0.2"
bitflags = "2.4"
foreign-types = "0.5"
libc = "0.2"
hex = "0.4"
rusty-hook = "^0.11"
futures = "0.3"
tokio = "1"
anyhow = "1"
antidote = "1.0.0"
linked_hash_set = "0.1"
openssl-macros = "0.1.1"
autocfg = "1.3.0"
brotli = "7.0"
