[package]
name = "rama-boring-tokio"
version = { workspace = true }
authors = [
    "Alex Crichton <alex@alexcrichton.com>",
    "Ivan Nikulin <ifaaan@gmail.com>",
    "Glen De Cauwsemaecker <glen@plabayo.tech>",
]
license = "MIT OR Apache-2.0"
edition = { workspace = true }
repository = { workspace = true }
homepage = "https://github.com/plabayo/rama-boring"
documentation = "https://docs.rs/rama-boring-tokio"
description = """
An implementation of SSL streams for Tokio backed by BoringSSL in function of Rama
"""

[package.metadata.docs.rs]
features = ["rpk", "pq-experimental"]
rustdoc-args = ["--cfg", "docsrs"]

[features]
# Use a FIPS-validated version of boringssl.
fips = ["rama-boring/fips", "rama-boring-sys/fips"]

# Use a FIPS build of BoringSSL, but don't set "fips-compat".
#
# As of boringSSL commit a430310d6563c0734ddafca7731570dfb683dc19, we no longer
# need to make exceptions for the types of BufLen, ProtosLen, and ValueLen,
# which means the "fips-compat" feature is no longer needed.
#
# TODO(cjpatton) Delete this feature and modify "fips" so that it doesn't imply
# "fips-compat".
fips-no-compat = ["rama-boring/fips-no-compat"]

# Link with precompiled FIPS-validated `bcm.o` module.
fips-link-precompiled = [
    "rama-boring/fips-link-precompiled",
    "rama-boring-sys/fips-link-precompiled",
]

# Enables experimental post-quantum crypto (https://blog.cloudflare.com/post-quantum-for-all/)
pq-experimental = ["rama-boring/pq-experimental"]

# Enables Raw public key API (https://datatracker.ietf.org/doc/html/rfc7250)
rpk = ["rama-boring/rpk"]

[dependencies]
rama-boring = { workspace = true }
rama-boring-sys = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true, features = ["full"] }
